### ISSUE TITLE
Replace AppVeyor with Travis-CI?

### ISSUE THREAD

**Issue by deeplook** [deeplook/svglib#241]
Travis-CI added support for Windows a while back, and we started at some point before to use AppVeyor for builds on Windows. I had looked previously at the config-fu needed to make it work with Travis-CI, and it is non-neglectable. But I have a tiny other project where somebody just added Windows support, so I wonder if we should also bundle all CI building and testing for different target platforms into one service? Any opinions?

This is the sample config mentioned above (see the matrix part): https://github.com/deeplook/mcinstall/blob/master/.travis.yml

**Comment by claudep** [comment]
No particular opinion on my side.

**Comment by NNTin** [comment]
Bear in mind Travis was acquired by Idera a year ago. A mass layoff followed. I personally use Azure Pipelines which also has Windows support. I also use Travis because that's what I've been originally using.

Travis had a good reputation but with the acquisition change can happen. So far it seems they haven't changed regarding their stance towards open source projects. They even recently added BitBucket. 

What I want to say is to make an informed decision and not base the decision solely on a single aspect which other services also provide. Travis might continue being awesome.

One important aspect is concurrent jobs. [There are some conflicting information.](https://travis-ci.community/t/concurrency-for-open-source-projects/3827) I currently have 5 concurrent jobs at Travis.   
Azure Pipelines offers 10. GitHub Actions offers 20. (GitHub Actions also has support for Windows.)  
This speeds up things a lot when you define different complicated test setups which can run in parallel. E.g. run tests for each platform and for major Python versions in parallel. Also when you have a really active repository you won't have a CI problem due to accumulated job backlog.

Just for the concurrent job workers I don't recommend Travis. Otherwise it is a fine service.

**Comment by deeplook** [comment]
@NNTin Thank you for your thoughts! That's exactly what I was trying to solicitate. I'm well aware of the issues with Travis CI. I guess it is just hard to find a good balance between using a set of distributed services, while optimizing for several criteria like functionality, stability, flexibility, ease-of-use and something else I might have forgotten.

**Comment by replabrobin** [comment]
FWIW I have just abandoned travis as a means of getting multibuild manylinux builds. It got slower and slower over the last year and they now have a token system. I already have appveyor building for windows and have moved the reportlab linux/macos building to github actions. I bit painful because  we are still using mercurial for scc, so a mirroring process is called for to take our repos into github, but the result is superior to travis.ci. I suspect github will (or perhaps already has) windows support (after all they are now part of the M$oft empire).

**Comment by claudep** [comment]
After 29733e6c1, we use now GitHub Actions.
