### ISSUE TITLE
The problem with converting the characters of the Russian alphabet from SVG to PDF

### ISSUE THREAD

**Issue by Dal-Opez** [deeplook/svglib#244]
Hello. Sorry for my english. When converting from SVG to PDF, the symbols of the Russian alphabet in the PDF file are replaced by black squares. Tell me, please, how to solve this problem?

**Comment by claudep** [comment]
Most probably svglib was not able to find the font file. You may have received some warnings in the command output.

**Comment by Dal-Opez** [comment]
there were no warnings

**Comment by claudep** [comment]
Maybe you could point us to that svg file?

**Comment by Dal-Opez** [comment]
I provide a file in PNG format. After downloading, change the format to SVG.
![RU_F1_v_6](https://user-images.githubusercontent.com/55364307/86904481-720cb500-c119-11ea-80f6-283128dd7e2f.png)

**Comment by claudep** [comment]
Thanks for that example. The problem is that the font is defined in your SVG with the `<font>`/`<glyph>` tags, which is not supported by svglib. As it seems to be deprecated (see https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font), we won't work on that support. You should update the svg to reference a real font instead.

**Comment by dantetemplar** [comment]
I have bumped into the very same issue. Is there any code example that works?
